server:
  globalauthcode: "auth"
  usessl: false
database:
  adapter: sqlite
  path: "./main2.db"
  # host: localhost
  # port: 1111
  # user: david
  # password: password
  # dbname: godb
  # path: ""