# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            CreoChain
tagline:          'An easy to use non distributed blockchain server'
description:      'An experimental, non-distributed, easily configurable blockchain server with guaranteed data integrity. Made with love by <a href="https://github.com/davidrzs/" target="_blank">davidrzs</a>.'
url:              https://davidrzs.github.io/
baseurl:          "/CreoChain/"

plugins:
  - jekyll-sitemap

author:
  name:           'davidrz'
  url:            https://davidrzs.github.io

github:
  repo: https://github.com/davidrzs/CreoChain

# Custom vars
version:          0.1.1
